import fs from 'node:fs';
import path from 'node:path';

import { GH_STRIP_VARS, GITHUB_HOST } from './constants.ts';
import { identityFunction } from './proc.ts';
import { buildPrompt, commentFiles, conveyorCommands, kitInputsValid, runFiles } from './prompt.ts';
import { writeTextAtomic } from './stateStore.ts';
import type { RunRecord } from './types.ts';
import { isValidNodeId, shQuote } from './validate.ts';

interface HookCommand {
    type: 'command';
    command: string;
}

interface HookEntry {
    matcher?: string;
    hooks: HookCommand[];
}

type HookKind = 'prompt' | 'stop' | 'permission' | 'tool';

const HOOK_FILE = 'hook.sh';
const LAUNCHER_FILE = 'launcher.sh';
const PROMPT_FILE = 'prompt.txt';
const SETTINGS_FILE = 'settings.json';
const GQL_DIR = 'gql';
const DECISION_GRACE_SECONDS = 5;
const PERMISSION_PATTERN = '"notification_type"[[:space:]]*:[[:space:]]*"permission_prompt"';
// Runs as claude's parent shell: records the shell's own identity token (identityFunction, the same token
// processStart reads) and pid, then execs claude in place, so both files describe claude itself (the pid and its
// start are unchanged by the exec). Claude starts only after a non-empty token and the pid were both written;
// otherwise the shell exits non-zero and the launcher records that status instead.
const CLAUDE_EXEC = `${identityFunction()}
prwc_identity $$ > "$1" && [ -s "$1" ] && echo $$ > "$2" && shift 2 && exec "$@"`;
// Stale values from a tmux server environment could point the conveyor's git at another repository or config.
const GIT_REDIRECT_VARS: readonly string[] = [
    'GIT_DIR',
    'GIT_WORK_TREE',
    'GIT_INDEX_FILE',
    'GIT_OBJECT_DIRECTORY',
    'GIT_ALTERNATE_OBJECT_DIRECTORIES',
    'GIT_CONFIG_PARAMETERS',
    'GIT_CONFIG_COUNT',
    'GIT_NAMESPACE',
    'GIT_COMMON_DIR',
];
const TOOL_MISMATCH = 'git or gh on PATH is not the one checked at start';

// One GraphQL document without variables, so the worker's gh call needs nothing but the file; the node id is
// validated, so no quote can reach the document.
export function buildReactionMutation(
    nodeId: string,
    action: 'add' | 'remove',
    content: 'EYES' | 'THUMBS_UP'
): string | undefined {
    if (!isValidNodeId(nodeId)) {
        return;
    }
    const name = `PrwcWorker${action === 'add' ? 'Add' : 'Remove'}${content === 'EYES' ? 'Eyes' : 'Plus1'}`;
    return `mutation ${name} { ${action}Reaction(input: { subjectId: "${nodeId}", content: ${content} }) { reaction { content } } }`;
}

function hookEntry(rd: string, kind: HookKind, matcher?: string): HookEntry {
    const hooks: HookCommand[] = [{ type: 'command', command: `/bin/sh ${shQuote(path.join(rd, HOOK_FILE))} ${kind}` }];
    return matcher === undefined ? { hooks } : { matcher, hooks };
}

// Rule paths use Claude Code's //absolute/path form: rd is absolute, so a leading slash is added. Edit rules cover
// every file-editing tool, Write included; Claude Code ignores Write(path) rules and warns about them at startup.
function allowRules(record: RunRecord, rd: string, commands: readonly string[]): string[] {
    const files = runFiles(rd);
    const replies = record.comments.map((comment) => commentFiles(rd, comment.dbId).reply);
    const writable = [...replies, files.commitMsg, files.prBody];
    return [`Read(/${rd}/**)`, ...writable.map((file) => `Edit(/${file})`), ...commands.map((line) => `Bash(${line})`)];
}

export function buildSettings(record: RunRecord, rd: string): string | undefined {
    const commands = conveyorCommands(record, rd);
    if (commands === undefined) {
        return;
    }
    const settings = {
        hooks: {
            UserPromptSubmit: [hookEntry(rd, 'prompt')],
            Stop: [hookEntry(rd, 'stop')],
            Notification: [hookEntry(rd, 'permission', 'permission_prompt')],
            PreToolUse: [hookEntry(rd, 'tool', '*')],
        },
        permissions: { allow: allowRules(record, rd, commands) },
    };
    return `${JSON.stringify(settings, undefined, 4)}\n`;
}

// Appends "KIND EPOCH" to the run's events file. It prints nothing (the output of a PreToolUse, Stop or
// UserPromptSubmit hook can be read as a decision or as context) and always exits 0; the input is drained and only
// matched, never stored. It runs its utilities from the system directories only, never from the inherited PATH, so
// nothing planted in the clone runs without a permission check.
export function buildHookScript(rd: string): string {
    const events = shQuote(path.join(rd, 'events'));
    return [
        '#!/bin/sh',
        '# Generated by pr-watch-comments: records one Claude Code hook event for the watcher.',
        'PATH=/usr/bin:/bin',
        'export PATH',
        'exec >/dev/null 2>&1',
        'kind=$1',
        'input=$(cat)',
        'case $kind in',
        'prompt | stop | tool) ;;',
        'permission)',
        String.raw`    printf '%s' "$input" | tr '\n\r\t' '   ' | grep -Eq ${shQuote(PERMISSION_PATTERN)} || exit 0`,
        '    ;;',
        '*) exit 0 ;;',
        'esac',
        String.raw`printf '%s %s\n' "$kind" "$(date +%s)" >> ${events}`,
        'exit 0',
        '',
    ].join('\n');
}

function launcherVariables(record: RunRecord, rd: string, launchWaitSeconds: number): string[] {
    const file = (name: string): string => shQuote(path.join(rd, name));
    return [
        `rd=${shQuote(rd)}`,
        `wait_seconds=${shQuote(String(launchWaitSeconds))}`,
        `decision_dir=${file('decision.d')}`,
        `value_file=${shQuote(path.join(rd, 'decision.d', 'value'))}`,
        `status_file=${file('exit_status')}`,
        `prompt_file=${file(PROMPT_FILE)}`,
        `settings_file=${file(SETTINGS_FILE)}`,
        `start_file=${file('claude.start')}`,
        `pid_file=${file('claude.pid')}`,
        `caller_path=${shQuote(record.callerPath)}`,
        `project_dir=${shQuote(record.dir)}`,
        `checked_git=${shQuote(record.git)}`,
        `checked_gh=${shQuote(record.gh)}`,
    ];
}

const LAUNCHER_FUNCTIONS: readonly string[] = [
    'write_status() {',
    `    printf '%s' "$1" >"$status_file" 2>/dev/null`,
    '}',
    '',
    'cancel_exit() {',
    '    write_status cancelled',
    '    exit 0',
    '}',
    '',
    'fallback_shell() {',
    '    exec "${SHELL:-/bin/sh}"',
    '}',
    '',
    'refuse() {',
    String.raw`    printf 'pr-watch-comments: %s; claude not started\n' "$1" >&2`,
    '    write_status cancelled',
    '    fallback_shell',
    '}',
    '',
    '# Prints where command -v finds the tool, with a leading // collapsed to / (PATH entry /), as preflight spells it.',
    'tool_path() {',
    '    found=$(command -v "$1") || return 1',
    '    while :; do',
    '        case $found in',
    '        //*) found=${found#/} ;;',
    '        *) break ;;',
    '        esac',
    '    done',
    `    printf '%s' "$found"`,
    '}',
    '',
    'decision() {',
    '    if [ -f "$value_file" ]; then',
    '        cat "$value_file" 2>/dev/null',
    '    fi',
    '}',
    '',
    '# Returns on go; exits on cancel, when the run directory is gone, and when no go arrives in time.',
    'await_go() {',
    '    waited=0',
    '    while :; do',
    '        if [ ! -d "$rd" ]; then exit 0; fi',
    '        case $(decision) in',
    '        go) return 0 ;;',
    '        cancel) cancel_exit ;;',
    '        esac',
    '        if [ "$waited" -ge "$wait_seconds" ]; then break; fi',
    '        sleep 1',
    '        waited=$((waited + 1))',
    '    done',
    '    if mkdir "$decision_dir" 2>/dev/null; then',
    `        printf 'cancel' >"$value_file.tmp.$$" 2>/dev/null && mv -f "$value_file.tmp.$$" "$value_file" 2>/dev/null`,
    '        cancel_exit',
    '    fi',
    '    grace=0',
    '    while :; do',
    '        if [ ! -d "$rd" ]; then exit 0; fi',
    '        case $(decision) in',
    '        go) return 0 ;;',
    '        cancel) cancel_exit ;;',
    '        esac',
    `        if [ "$grace" -ge ${DECISION_GRACE_SECONDS} ]; then cancel_exit; fi`,
    '        sleep 1',
    '        grace=$((grace + 1))',
    '    done',
    '}',
];

function launcherMain(record: RunRecord): string[] {
    const claudeWords = [record.claude, ...record.claudeArgs].map((word) => shQuote(word)).join(' ');
    return [
        'await_go',
        `unset ${GH_STRIP_VARS.join(' ')}`,
        `unset ${GIT_REDIRECT_VARS.join(' ')}`,
        `GH_HOST=${GITHUB_HOST}`,
        'export GH_HOST',
        'prompt=$(cat "$prompt_file")',
        'prompt_status=$?',
        'PATH=$caller_path',
        'export PATH',
        `if [ "$prompt_status" -ne 0 ]; then refuse 'the run prompt is unreadable'; fi`,
        `cd "$project_dir" || refuse 'the project directory is not reachable'`,
        'if [ "$(tool_path git)" != "$checked_git" ] || [ "$(tool_path gh)" != "$checked_gh" ]; then',
        `    refuse ${shQuote(TOOL_MISMATCH)}`,
        'fi',
        `/bin/sh -c ${shQuote(CLAUDE_EXEC)} sh "$start_file" "$pid_file" ${claudeWords} --settings "$settings_file" -- "$prompt"`,
        'write_status "$?"',
        'fallback_shell',
    ];
}

// POSIX sh run as the worker pane's command through /bin/sh. Every value is embedded at generation as one
// single-quoted word, so the worker never depends on the plugin install path. The handshake runs with the standard
// utility directories on PATH; the caller's PATH is exported only for the tool check and claude.
export function buildLauncherScript(record: RunRecord, rd: string, launchWaitSeconds: number): string | undefined {
    if (!kitInputsValid(record, rd) || !Number.isSafeInteger(launchWaitSeconds) || launchWaitSeconds <= 0) {
        return;
    }
    return [
        '#!/bin/sh',
        '# Generated by pr-watch-comments: starts claude for one run once the watcher has decided go.',
        'PATH=/usr/bin:/bin',
        'export PATH',
        ...launcherVariables(record, rd, launchWaitSeconds),
        '',
        ...LAUNCHER_FUNCTIONS,
        '',
        ...launcherMain(record),
        '',
    ].join('\n');
}

// The three reaction documents of one comment, or undefined when its node id is refused.
function commentMutations(rd: string, nodeId: string, dbId: number): [string, string][] | undefined {
    const files = commentFiles(rd, dbId);
    const removeEyes = buildReactionMutation(nodeId, 'remove', 'EYES');
    const removePlus1 = buildReactionMutation(nodeId, 'remove', 'THUMBS_UP');
    const addPlus1 = buildReactionMutation(nodeId, 'add', 'THUMBS_UP');
    if (removeEyes !== undefined && removePlus1 !== undefined && addPlus1 !== undefined) {
        return [
            [files.removeEyes, `${removeEyes}\n`],
            [files.removePlus1, `${removePlus1}\n`],
            [files.addPlus1, `${addPlus1}\n`],
        ];
    }
    return;
}

function buildKit(record: RunRecord, rd: string, launchWaitSeconds: number): [string, string][] | undefined {
    const prompt = buildPrompt(record, rd);
    const settings = buildSettings(record, rd);
    const launcher = buildLauncherScript(record, rd, launchWaitSeconds);
    const mutations = record.comments.map((comment) => commentMutations(rd, comment.nodeId, comment.dbId));
    const documents = mutations.filter((files) => files !== undefined).flat();
    if (prompt !== undefined && settings !== undefined && launcher !== undefined && !mutations.includes(undefined)) {
        return [
            [path.join(rd, PROMPT_FILE), prompt],
            [path.join(rd, SETTINGS_FILE), settings],
            [path.join(rd, HOOK_FILE), buildHookScript(rd)],
            [path.join(rd, LAUNCHER_FILE), launcher],
            ...documents,
        ];
    }
    return;
}

// Creates gql/ inside an existing run directory; an existing entry is accepted only when it is a real directory.
function ensureGqlDir(rd: string): void {
    const dir = path.join(rd, GQL_DIR);
    try {
        fs.mkdirSync(dir, { mode: 0o700 });
    } catch (error) {
        if (!fs.lstatSync(dir).isDirectory()) {
            throw error;
        }
    }
}

// Writes the whole worker kit into the run directory, or nothing when any builder refuses. The scripts are run
// through /bin/sh, so every file is owner-only and none is executable.
export function writeWorkerKit(rd: string, record: RunRecord, launchWaitSeconds: number): boolean {
    const kit = buildKit(record, rd, launchWaitSeconds);
    if (kit === undefined) {
        return false;
    }
    try {
        ensureGqlDir(rd);
        for (const [file, text] of kit) {
            writeTextAtomic(file, text);
        }
    } catch {
        return false;
    }
    return true;
}
